Undo system
calband/calchart-redesign pull request #150
Opened 2021-02-07 07:27 UTC by rmpowell77

This closely follows the outline by Anthony Gore:
https://vuejsdevelopers.com/2017/11/13/vue-js-vuex-undo-redo/

What we do is we have the undo system implemented as a stack of Store Commit changes. When we do an undo, we go back to an initial state and redo all of the Store commit commands. With CalChart, not every Store commit is a change we want to undo, so we have a filter where we only save certain commits.

Adding bottom row buttons
using hotkeys.
adding File/Edit menu.

## Pre-PR checklist

- [ ] Ran `npm run serve` and:
  - [ ] Checked basic functionality
  - [ ] Checked that errors are handled
- [ ] Ran `npm run lint`
- [ ] Ran `npm run test:unit`
- [ ] Ran `npm run test:e2e` and ran relevant tests
- [ ] Attached reviewers to PR and pinged on Slack/email

## Screenshots/GIFs

[Attach screenshots if making a visible change!]

2021-02-20 21:46 UTC, vhlee7 commented
bug: undo with adding/removing sheets

2021-03-20 21:01 UTC, vhlee7 commented
meeting notes:

current issues:
dots are not connected to their continuities
    -dots do not regenerate flows
when moving dot, state has updated but not the dot image


grapher don't observe state but flows
    - move flow outside of the show object

new issue:
watches to auto regenerate the flow
    
flow watching the state or vice versa

2021-04-07 02:41 UTC, kmdurand approved these changes

2021-04-24 21:14 UTC, rmpowell77 commented
Looks like this is still failing if you do the following:

Add a sheet, remove a sheet.

We need to make sure we reset these to 0:

selectedSS
selectedDotIDs
beat
grapherToolDots

2021-06-12 20:38 UTC, rmpowell77 commented
Let's rethink this and go with a system that makes snapshots of the Show state, and then restores those snapshot.

2021-06-18 22:02 UTC, rmpowell77 commented
Updated to be based on a snapshotting system.

2021-06-22 04:13 UTC, MichaelTamaki approved these changes
Thank you for the work on this! Left some suggestions.

2021-06-22 04:13 UTC, MichaelTamaki commented on src/components/menu-top/MenuTop.vue
> +          <b-navbar-item data-test="menu-top--edit-undo" @click="undo">
A suggestion to keep on our backlog: Investigate disabling the Undo/Redo navbar items if there is nothing to undo/redo, similar to the bottom menu

2021-06-22 04:13 UTC, MichaelTamaki commented on src/models/Show.ts
> + * These would be items we would want to be saved and restored, or undoable.
Nice! Have you considered creating a higher level model that contains `Show` and the undoable metadata (`selectedSS`, etc)?

For example, what if we create a new model called something like `SavedState`, with properties `show`, `selectedSS`, `beat`, and `selectedDotIds`? And we have a new mutation for setting the new `SavedState`. This way the `Show` model can be solely focused on show data.

2021-06-22 04:13 UTC, MichaelTamaki commented on src/models/UndoRedo.ts
> +// The UndoRedo holds snapshots of the show over time.
nit: feel free to use the long comment syntax for this multi-line comment, VSCode should format it for you automatically!

```js
/**
 * Multi-level comment
 * Multi-level comment
 */
```

2021-06-22 04:13 UTC, MichaelTamaki commented on src/models/UndoRedo.ts
> +// here is a diagram of what we expect to occur with a series of commits, undo, redo actions.
Thanks for the explanation and example! Can you also add in the link to the article you got inspiration from? https://vuejsdevelopers.com/2017/11/13/vue-js-vuex-undo-redo/

2021-06-22 04:13 UTC, MichaelTamaki commented on src/models/UndoRedo.ts
> +  maxSnapshots = 10;
Curious, have you experimented to see how large you could make this? Another future improvement could be to allow the user to modify this limit.

2021-06-22 04:13 UTC, MichaelTamaki commented on src/models/UndoRedo.ts
> +      this.stateSnapshots = [[JSON.stringify(store.state.show), ""]];
Could we re-use code here?
```suggestion
      reinitializeUndoRedo(store.state.show);
```

2021-06-22 04:13 UTC, MichaelTamaki commented on src/models/UndoRedo.ts
> +            );
Consider using the `Array.prototype.shift()` instead! https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift
```suggestion
            this.stateSnapshots.shift();
```

2021-06-22 04:13 UTC, MichaelTamaki approved these changes
Thank you for the work on this! Left some suggestions.

2021-06-26 16:52 UTC, rmpowell77 commented on src/components/menu-top/MenuTop.vue
> +          <b-navbar-item data-test="menu-top--edit-undo" @click="undo">
Tracking already with #131

2021-06-26 16:56 UTC, rmpowell77 commented on src/models/Show.ts
> + * These would be items we would want to be saved and restored, or undoable.
I'm feeling we should model the `Show` object as that state.  I think values like `selectedSS` ,`beat`, and `selectedDotIds` are actually part of the `Show`, so it's appropriate to put all those values in there.  This is actually how we do CalChart 3.

2021-06-26 17:00 UTC, rmpowell77 commented on src/models/UndoRedo.ts
> +// The UndoRedo holds snapshots of the show over time.
👍

2021-06-26 17:00 UTC, rmpowell77 commented on src/models/UndoRedo.ts
> +// here is a diagram of what we expect to occur with a series of commits, undo, redo actions.
👍

2021-06-26 17:04 UTC, rmpowell77 commented on src/models/UndoRedo.ts
> +      this.stateSnapshots = [[JSON.stringify(store.state.show), ""]];
👍

2021-06-26 17:10 UTC, rmpowell77 commented on src/models/UndoRedo.ts
> +  maxSnapshots = 10;
Yes, we should probably have something like #183 `Undo system should be based on memory limit a user can set`.
But we would also need something like #184 `Saving a file should save only the parts that are needed`
so we can make the files smaller.

2021-06-26 17:13 UTC, rmpowell77 commented on src/models/UndoRedo.ts
> +            );
Awesome, I was looking for that

2021-06-28 02:04 UTC, adhamrait requested changes, later dismissed
I like the snapshot idea compared to the equal-and-opposite solution the undoable-action-list solution. I found a bug while testing it out and I included a video in the slack channel! Also a few other smaller bugs that I found:

- Dot type appearance changes are not undoable
- Undoing will reset the selected beat to Hup/0

I think 10 undos total is a bit on the shorter side but we can address that when we get #183  and  #184.

2021-06-28 02:04 UTC, adhamrait commented on src/models/UndoRedo.ts
> + * Inspiration for the undo system from https://vuejsdevelopers.com/2017/11/13/vue-js-vuex-undo-redo/
Thank you for writing this out!

2021-07-04 06:21 UTC, rmpowell77 commented
I fixed up the bug, but I don't think I can merge till the approvals are done.

2021-07-10 20:20 UTC, merged