Shunt sheet browser
calband/calchart-redesign pull request #47
Opened 2019-12-31 17:13 UTC by rmpowell77

This builds on #40, so requires that to be merged first.

This is sort of a WIP, looking for feedback.  This will create a preview sheet for each stunt sheet on the left hand side.  Except it isn't drawing dots, isn't scaling, and isn't setting up scroll bars if there are too many sheets...  Besides that, it's pretty interesting change.

2019-12-31 17:46 UTC, MichaelTamaki commented
👍 Thank you for the head start, I’ll look at this later. Can you change the PR branch from master to the branch in #40? That way it’ll be easier to view the changes.

it might be difficult to complete the stuntsheet previews right now as we haven’t even finished drawing dots on the main grapher yet. I think for now, you could focus on just having a stuntsheet list without the preview, or work on a different issue?

2019-12-31 22:57 UTC, rmpowell77 commented
Oh, this also contains drawing the dots -- though they aren't in the right place yet.  Think of this PR as an early preview to get feedback on the formatting.

2020-01-22 08:21 UTC, MichaelTamaki commented
I've been thinking about actually saving the SVGs as pictures, which we use as the preview. Not sure if this is actually possible, but it would save the browser from having to render every single stuntsheet all the time.

2020-02-01 21:28 UTC, MichaelTamaki requested changes
Found a fix to the scroll bar issue. It's in regards to flexbox, which is kinda tricky and takes a bit to understand. See this guide if you're interested in learning about it: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

In `MenuLeft.vue`, add `overflow-y: auto;`
```scss
.menu-left {
  width: 150px;
  overflow-y: auto;
}
```

In `App.vue`, add `min-height: 0;` to `.app--bottom`:
```scss
.app--bottom {
  flex: 1 1;
  // eslint-disable-next-line max-len
  // https://stackoverflow.com/questions/34144972/flexbox-avoid-child-with-longer-height-than-parent-column-direction
  min-height: 0;
}
```

Also see my comment regarding parking the stuntsheet preview functionality for now. I'd suggest either making simple stuntsheet controls or working on a different issue.

2020-02-01 21:28 UTC, MichaelTamaki commented on src/components/grapher/PerSheetPreview.vue
> +    <svg class="persheetpreview-svg"><g>
I think for now, we should park the sheet preview feature. I feel that `Grapher` is going to be changing a lot in the coming months, so if we had both `Grapher` and `PerSheetPreview`, we'd have to worry about and modify both whenever there's a change.

For now, how about we just have a simple stuntsheet selector and add/remove functionality?

2020-02-01 21:28 UTC, MichaelTamaki commented on src/components/menu-left/MenuLeft.vue
> +    <section>
`section` and `footer` are good for semantics in websites, but for web applications they sometimes add unnecessary default styling. We should use `div` instead.

2020-02-01 21:28 UTC, MichaelTamaki commented on src/models/StuntSheet.ts
> + * @property title          - Title of this StuntSheet
For property descriptions, it's more helpful if you use words that are not the property name. In this case, using `Title of this Stuntsheet` to describe `title` doesn't really add any additional insight into what `title` is used for... After all, the property name is `title` inside the `Stuntsheet` model.

2020-02-01 21:28 UTC, MichaelTamaki commented on src/components/menu-left/MenuLeft.vue
> +      <b-button
We could consider using a number input from Buefy instead, which is basically the same thing: https://buefy.org/documentation/numberinput

2020-02-17 00:03 UTC, MichaelTamaki commented
@rmpowell77 FYI I'm going to make a simple PR for selecting/adding/removing stunt sheets so that I can start working on the continuity editor after that. We can keep this PR so we can track whether or not it's feasible to create an SVG for each stuntsheet.

2020-02-17 00:21 UTC, MichaelTamaki commented
https://github.com/calband/calchart-redesign/pull/68

2021-01-18 21:21 UTC, closed without merging

2021-01-18 21:21 UTC, MichaelTamaki commented
Will finalize later. Will get to this at a later date when higher priorities are done. https://github.com/calband/calchart-redesign/issues/34